export const Users = [
    {
        id:1,
        profilePicture: "1/cr7.jpeg",
        username: "cr7",
    },
    {
        id:2,
        profilePicture: "1/francis.jpeg",
        username: "francis",
    },
    {
        id:3,
        profilePicture: "1/gennady.jpeg",
        username: "tourist",
    },
    {
        id:4,
        profilePicture: "1/khabib.jpeg",
        username: "khabib",
    },
    {
        id:5,
        profilePicture: "1/mcgreror.jpeg",
        username: "conor",
    },
    {
        id:6,
        profilePicture: "1/messi.jpeg",
        username: "messi",
    },
    {
        id:7,
        profilePicture: "1/mike_tyson.jpeg",
        username: "mike tyson",
    },
    {
        id:8,
        profilePicture: "1/musiala.jpeg",
        username: "musiala",
    },
    {
        id:9,
        profilePicture: "1/neymar.jpeg",
        username: "neymar",
    },
    {
        id:10,
        profilePicture: "1/pedri.jpeg",
        username: "pedri",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "2/cr7.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "2/cr7.jpeg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "2/download.jpeg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "2/download.jpeg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "2/khabib.jpeg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "2/khabib.jpeg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "2/messi.jpeg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "2/messi.jpeg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "2/miketyson.jpeg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "2/miketyson.jpeg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];